version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_movieDB
    environment:
      MYSQL_ROOT_PASSWORD: premier-picks
      MYSQL_DATABASE: movieDB
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - movieDB-network

networks:
  movieDB-network:
    driver: bridge